/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import tictactoe.Game.STATUS;

/**
 *
 * @author anatoliy
 */
public class TicTacToe extends javax.swing.JFrame {
   
    private Game game = new Game();
    private static final String DEFAULT = "Ваш ход";
    private static final String TIC_WIN = "Выиграли нолики";
    private static final String TAC_WIN = "Выиграли крестики";
    private static final String STANDOFF = "Ничья";
   
    STATUS currentState;
    
    private final String[] TIC_TAC = {"Крестики", "Нолики"};
    
    public TicTacToe() {
        initComponents();
        enableFieldViews();
    }
    
    private void enableFieldViews() {
        fieldButton1.setEnabled(true);
        fieldButton1.setText("");
        fieldButton2.setEnabled(true);
        fieldButton2.setText("");
        fieldButton3.setEnabled(true);
        fieldButton3.setText("");
        fieldButton4.setEnabled(true);
        fieldButton4.setText("");
        fieldButton5.setEnabled(true);
        fieldButton5.setText("");
        fieldButton6.setEnabled(true);
        fieldButton6.setText("");
        fieldButton7.setEnabled(true);
        fieldButton7.setText("");
        fieldButton8.setEnabled(true);
        fieldButton8.setText("");
        fieldButton9.setEnabled(true);
        fieldButton9.setText("");
    }
    
    private void disableFieldViews() {
        fieldButton1.setEnabled(false);
        fieldButton2.setEnabled(false);
        fieldButton3.setEnabled(false);
        fieldButton4.setEnabled(false);
        fieldButton5.setEnabled(false);
        fieldButton6.setEnabled(false);
        fieldButton7.setEnabled(false);
        fieldButton8.setEnabled(false);
        fieldButton9.setEnabled(false);
    }
    
    private void drawField(){
        int[][][] gameDrawedField = game.getField();
        for (int x = 0; x < 3; x++) {
            for (int y = 0; y < 3; y++) {
                drawSectorField(x, y, gameDrawedField[x][y][0]);
            }
        }
        currentState = game.getStatus();
        if (null != currentState)
            switch (currentState) {
           case STARTED:
               jLabel1.setText(DEFAULT);
               break;
           case FINISHED_TIC:
               jLabel1.setText(TIC_WIN);
               disableFieldViews();
               break;
           case FINISHED_TAC:
               jLabel1.setText(TAC_WIN);
               disableFieldViews();
               break;
           case FINISHED_STANDOFF:
               jLabel1.setText(STANDOFF);
               break;
           default:
               break;
       }
    }
    
    private void drawSectorField(int x, int y, int z) {
        if (x == 0 && y == 0 && z != 0) {
            fieldButton1.setText("" + (char)z);
            fieldButton1.setEnabled(false);
        }
        else if (x == 0 && y == 1 && z != 0) {
            fieldButton2.setText("" + (char)z);
            fieldButton2.setEnabled(false);
        }
        else if (x == 0 && y == 2 && z != 0) {
            fieldButton3.setText("" + (char)z);
            fieldButton3.setEnabled(false);
        }
        else if (x == 1 && y == 0 && z != 0) {
            fieldButton4.setText("" + (char)z);
            fieldButton4.setEnabled(false);
        }
        else if (x == 1 && y == 1 && z != 0) {
            fieldButton5.setText("" + (char)z);
            fieldButton5.setEnabled(false);
        }
        else if (x == 1 && y == 2 && z != 0) {
            fieldButton6.setText("" + (char)z);
            fieldButton6.setEnabled(false);
        }
        else if (x == 2 && y == 0 && z != 0) {
            fieldButton7.setText("" + (char)z);
            fieldButton7.setEnabled(false);
        }
        else if (x == 2 && y == 1 && z != 0) {
            fieldButton8.setText("" + (char)z);
            fieldButton8.setEnabled(false);
        }
        else if (x == 2 && y == 2 && z != 0) {
            fieldButton9.setText("" + (char)z);
            fieldButton9.setEnabled(false);
        }
    }
    
    private void gameStep(int x, int y) {
        game.gameStep(x, y);
        game.compStep();
        drawField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldButton1 = new javax.swing.JButton();
        fieldButton2 = new javax.swing.JButton();
        fieldButton3 = new javax.swing.JButton();
        fieldButton4 = new javax.swing.JButton();
        fieldButton5 = new javax.swing.JButton();
        fieldButton6 = new javax.swing.JButton();
        fieldButton7 = new javax.swing.JButton();
        fieldButton8 = new javax.swing.JButton();
        fieldButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldButton1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fieldButton1.setFocusPainted(false);
        fieldButton1.setMaximumSize(new java.awt.Dimension(94, 94));
        fieldButton1.setMinimumSize(new java.awt.Dimension(94, 94));
        fieldButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton1MouseClicked(evt);
            }
        });

        fieldButton2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton2.setFocusPainted(false);
        fieldButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton2MouseClicked(evt);
            }
        });

        fieldButton3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton3.setFocusPainted(false);
        fieldButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton3MouseClicked(evt);
            }
        });

        fieldButton4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton4.setFocusPainted(false);
        fieldButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton4MouseClicked(evt);
            }
        });

        fieldButton5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton5.setFocusPainted(false);
        fieldButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton5MouseClicked(evt);
            }
        });

        fieldButton6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton6.setFocusPainted(false);
        fieldButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton6MouseClicked(evt);
            }
        });

        fieldButton7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton7.setFocusPainted(false);
        fieldButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton7MouseClicked(evt);
            }
        });

        fieldButton8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton8.setFocusPainted(false);
        fieldButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton8MouseClicked(evt);
            }
        });

        fieldButton9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        fieldButton9.setFocusPainted(false);
        fieldButton9.setPreferredSize(new java.awt.Dimension(94, 94));
        fieldButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldButton9MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ваш ход");

        jButton10.setText("Заново");
        jButton10.setFocusPainted(false);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(TIC_TAC));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton1MouseClicked
        if (this.fieldButton1.isEnabled()) {
            game.gameStep(0, 0);
            game.compStep();
            drawField();
        }
    }//GEN-LAST:event_fieldButton1MouseClicked

    private void fieldButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton2MouseClicked
        if (this.fieldButton2.isEnabled()) {
            this.gameStep(0, 1);
        }
    }//GEN-LAST:event_fieldButton2MouseClicked

    private void fieldButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton3MouseClicked
        if (this.fieldButton3.isEnabled()) {
            this.gameStep(0, 2);
        }
    }//GEN-LAST:event_fieldButton3MouseClicked

    private void fieldButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton4MouseClicked
        if (this.fieldButton4.isEnabled()) {
            this.gameStep(1, 0);
        }
    }//GEN-LAST:event_fieldButton4MouseClicked

    private void fieldButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton5MouseClicked
        if (this.fieldButton5.isEnabled()) {
            this.gameStep(1, 1);
        }
    }//GEN-LAST:event_fieldButton5MouseClicked

    private void fieldButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton6MouseClicked
        if (this.fieldButton6.isEnabled()) {
            this.gameStep(1, 2);
        }
    }//GEN-LAST:event_fieldButton6MouseClicked

    private void fieldButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton7MouseClicked
        if (this.fieldButton7.isEnabled()) {
            this.gameStep(2, 0);
        }
    }//GEN-LAST:event_fieldButton7MouseClicked

    private void fieldButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton8MouseClicked
        if (this.fieldButton8.isEnabled()) {
            this.gameStep(2, 1);
        }
    }//GEN-LAST:event_fieldButton8MouseClicked

    private void fieldButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldButton9MouseClicked
        if (this.fieldButton9.isEnabled()) {
            this.gameStep(2, 2);
        }
    }//GEN-LAST:event_fieldButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        if (jComboBox1.getSelectedItem().toString().equals(TIC_TAC[0])) {
            game.setOrder(Game.ORDER.TAC);
        }
        else game.setOrder(Game.ORDER.TIC);
        game.startAgain();
        enableFieldViews();
        drawField();
    }//GEN-LAST:event_jButton10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TicTacToe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fieldButton1;
    private javax.swing.JButton fieldButton2;
    private javax.swing.JButton fieldButton3;
    private javax.swing.JButton fieldButton4;
    private javax.swing.JButton fieldButton5;
    private javax.swing.JButton fieldButton6;
    private javax.swing.JButton fieldButton7;
    private javax.swing.JButton fieldButton8;
    private javax.swing.JButton fieldButton9;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}